{% set name = "f90nml" %}
{% set version = "1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/f90nml-{{ version }}.tar.gz
  sha256: d5585f0051234c742f7515c4b1f8484f8f628a71c4e31f2602357089dcc05fc1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - f90nml
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/marshallward/f90nml
  summary: Fortran 90 namelist parser
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jacobwilliams
    - MuellerSeb
