{% set name = "f90nml" %}
{% set version = "1.4.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/f90nml-{{ version }}.tar.gz
  sha256: 65e8e135779895245238cbf6be5b1b80d6c2b8c9350c9cdce6183a31bdfd7622

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7

test:
  imports:
    - f90nml
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/marshallward/f90nml
  summary: Fortran 90 namelist parser
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cpelley
    - MuellerSeb
