{% set version = "1.1.2" %}
{% set sha256 = "c5f29e4b7159f0db8a9cfe801b692384a603f2cb40f5da1c038897eb98064f7d" %}

package:
  name: f90nml
  version: {{ version }}

source:
  fn: f90nml-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/f/f90nml/f90nml-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - f90nml

about:
  home: http://github.com/marshallward/f90nml
  license: Apache-2.0
  summary: 'Fortran 90 namelist parser'
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cpelley
