{% set version = "1.1.1" %}
{% set sha256 = "210358fc272580e3cb461a5bb3c8f8a0d373a78fe3d65ee8bbbe321d4b71525e" %}

package:
  name: f90nml
  version: {{ version }}

source:
  fn: f90nml-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/f/f90nml/f90nml-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - f90nml

about:
  home: http://github.com/marshallward/f90nml
  license: Apache-2.0
  summary: 'Fortran 90 namelist parser'
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cpelley
