{% set version = "1.2" %}
{% set sha256 = "07fbb9101f218ce89ccc34264ec81116edc9ed0ab69ad1cd8316f19ea694cd2e" %}

package:
  name: f90nml
  version: {{ version }}

source:
  fn: f90nml-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/f/f90nml/f90nml-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - f90nml

about:
  home: http://github.com/marshallward/f90nml
  license: Apache-2.0
  summary: Fortran 90 namelist parser
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cpelley
