{% set version = "1.0.2" %}
{% set sha256 = "cfebfc34dd8969b1a9424363407ca7915481f47377819b204eaa08140fd4e7bb" %}

package:
  name: f90nml
  version: {{ version }}

source:
  fn: f90nml-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/f/f90nml/f90nml-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - f90nml

about:
  home: http://github.com/marshallward/f90nml
  license: Apache-2.0
  summary: 'Fortran 90 namelist parser'
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cpelley
