{% set version = "0.21" %}
{% set sha256 = "df0538bfd977f6e72d3bbf6beb8bd7dc7c01882d5a89e99fbfdfbf1aa5b24b8b" %}

package:
  name: f90nml
  version: {{ version }}

source:
  fn: f90nml-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/f/f90nml/f90nml-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - f90nml

about:
  home: http://github.com/marshallward/f90nml
  license: Apache-2.0
  summary: 'Fortran 90 namelist parser'
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cpelley
