appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Yymktttron6MYGaurbdSXcLNLdSx6R17xeMWGrwATaSqclkmTHRGQCpeh+xG2b0I7Uyz6tuUs0FhhL5QDCLjLZnEfRIXWDvv8+sOxPKn+DUgXP/QV9jvLBxpGYL0OrfC0Tid+EcMln7cIZbcepgbyosU8z95l62RWjOgp4rbKDG6jjiv7MAX5kDkg1fZsbSRbnsU9plm17fZSKCzpa9C0ikTPuEiYL19dAhV/NOHaZv2UzcFnMzovioyNpr285dremMk2IpPYRRas9WSatFDMjI0o8KA1OU59E8AADG0U6n5L3x5rGZSEKLBMR+y26xjejPfG4Jb3FdBj4nTckDictpm/qlxe+KtnkrUUvTAFUgEWTVBNkgEqmAXUMflX9W9Nnq/0XDe6jTAF3iyD65pJhKSd0WICGSvpSOsh50VLTWgA5JZq654lYRfnKCQC7KFQoyDFcUQi6cs7dJhEvmbV4ycT0r/RdLeAVqfngbelKnz94xuHTncH3WE/ToZmv4zIu0wuOPfNdsZbmU8PlL5kE03Za4gW3IZkV8GMNN0+8uGwI529ZMHhk8an/LzBrk1HRXVb7gVTDexELAY3wxAEiJbA6bip3cRAEgiTJfpVdhNusfsZVcxLMBZ8p8snW9l9Zd//KmuB7yrHBt78PK87+wk5cKTWoXNPx4qaYo67jA=}
provider:
  win: azure
