travis:
  secure:
    BINSTAR_TOKEN: kglpM0UBuD0r+SBdMh5Ld/EySBzhDABFgEKI+okpyXB0jHbTpq7nFWz07bUQ9BhhE2HJ694mTwyTDxQO/jnQii4HmY0zZ4UTTpgVJ62DYThfubShV02pxHsBf47L4h4+VwzSWXGmdkV6fiN7UEBoNq9g/xACtMpRKAHhghqH6QCChodAungXOExOYSIFlcTQXvur04hvWUW+LbPkZ3JnpgHciiK7VShM6ctrHPBjkqLLXZG+dre7fCUc2+vjAgZhzcAdvompMenXkDNwvRVguxyc4WRhKJbuGytqGlg5Jle7cCUUp/ichW2JDJh5bo+qMytfnzQmSxY0KDmTLyzVMNHAD+B8pRgUKAbbbdYcNmT4tpO6u4Ck7Jj/OyWtZCN+shXFBx3IHmg4qpBsv52kpXj4W0UfvVbPwzMI2Kp1BE9ijfm9uuQWVzOkAR+Bs9bdeG3QVxejwqkAF2omAm2oOitCKnPMDt7yhKjff5bucedO5trE8O6VTeW7ussjJOFxQoRflku63AhF0UqhuizBpJpt6vtPo0t3OyV840sH1oLYQaPpkQh/7x7D/phEuEbWnp+D7sBLyCx5RufOzQIa3f2sTIwHnQFcZtPhctvEDVQCwNET8doxRm03O82Hi8fNWX6SACooDCWHtSgRPeRncGoUWHDNLg7VwNUUU+AQ3iw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
